disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Alex White"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "badlogo.png"

[[params.author.links]]
email = "mailto:alex.white@hey.com"

[[params.author.links]]
github = "https://github.com/devalexwhite/"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/devalexwhite/"

["params.author"]
name = "Alex White"
headline = "Just a dad."
bio = "Dad, cyclist and tech guy living in Ohio."
image = "profile.jpg"
